baseURL = 'https://zenpylon.me/'
languageCode = 'en-us'
title = 'Andrew Decker'
theme = 'hermit-v2'


[params]
  homeSubtitle = "code, creativity, curiosity"
  homeSubtitlePrinter = true
  
  author.name = "Andrew Decker"
  
  [[params.socialLinks]]
    name = "email"
    url = "mailto:ajdecker1022@gmail.com"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/ZenPylon"

  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ajdecker1022/"
  
[menu]

[[menu.main]]
  name = "Posts"
  url = "posts/"
  weight = 10

[[menu.main]]
  name = "About"
  url = "about"
  weight = 20